setup_mlflow: true
mlflow_autolog: false
mlflow_tracking_uri: "https://mlflow.aiap19.aisingapore.net"
mlflow_exp_name: "isaacb_kam_jk_cv-presentation"
# mlflow_run_name: "densenet121-test-adamw"
resume: false
mlflow_run_name: "vit_b_16" 
train_bs: 32
seed: 1111
epochs: 1
model_checkpoint_dir_path: "./models"
log_dir: "./logs/models"
lr: 1e-4
image_size: 224 # the following image sizes are available: 32 or 224
cv_architecture: "vit_b_16" # the following are available: resnet18, densenet121, vit_b_16, googlenet
freeze_backbone: false
device: "cuda" #for gpu (cuda), or cpu (cpu)
optimiser: "AdamW" #the following image sizes are available: Adam or AdamW
weight_decay: 0.05

transforms:
  train:
    - _target_: albumentations.RandomResizedCrop
      size: [224, 224]
      scale: [0.08, 1.0]
      ratio: [0.75, 1.33]
      p: 1.0
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    - _target_: albumentations.Rotate
      limit: 25
      p: 0.5
    - _target_: albumentations.ColorJitter
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      p: 0.8
    - _target_: albumentations.CoarseDropout
      num_holes_range: [1, 2]
      hole_height_range: [0.1, 0.2]
      hole_width_range: [0.1, 0.2]
      fill: 0
      p: 0.5
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.transforms.ToTensorV2
